### ISSUE TITLE
Address deprecations on Scala 2.13 and remove silencer.

### ISSUE THREAD

**Issue by rpiaggio** [gemini-hlsw/gsp-core#46]
Deprecation warnings in Scala 2.13 are:

- Number`.signum` --> `.sign`.
- Iterable`.toIterator` --> `.iterator`.
- Sorted`.from`, `.to` --> `.rangeFrom`, `.rangeTo`
- Scala's `Stream` --> `LazyList`.

**Comment by cquiroz** [comment]
Is this still valid?

**Comment by rpiaggio** [comment]
Yes. I think we can stop cross-compiling to 2.12 now. We should do the substitutions described above, it _probably_ shouldn't be more than find & replace and remove silencer from `build.sbt`. I can look into it.

**Comment by tpolecat** [comment]
Yes, I think we can stop publishing for 2.12 and then do the same for gsp-math.
